const ID="13bEDi4qQHvfYnOBOQiYgD4HSxlNAK6YWWrAkCkkikOQ",GID="0";const CSV=`https://docs.google.com/spreadsheets/d/${ID}/export?format=csv&gid=${GID}`;let data=[];
const $=id=>document.getElementById(id),money=n=>"$"+Math.round(n||0).toLocaleString("en-US");
function num(v){return Number(String(v??"").replace(/[$,%\s,]/g,""))||0}
function csv(s){let a=[],r=[],c="",q=false;for(let i=0;i<s.length;i++){let x=s[i],n=s[i+1];if(x=='"'&&q&&n=='"'){c+='"';i++;continue}if(x=='"'){q=!q;continue}if(x==","&&!q){r.push(c);c="";continue}if((x=="\n"||x=="\r")&&!q){if(x=="\r"&&n=="\n")i++;r.push(c);c="";if(r.some(v=>v.trim()))a.push(r);r=[];continue}c+=x}r.push(c);if(r.some(v=>v.trim()))a.push(r);return a}
function level(x){let p=x.target?x.actual/(x.target*2):0;return p>=1.5?["🔥","Legend 150%",p]:p>=1.2?["🚀","Elite 120%",p]:p>=1?["⚡","Pro 100%",p]:["🌱","Start",p]}
function reward(x){let t=x.target*3;if(x.actual<t)return 0;if(x.target>=350000)return 6000+Math.floor((x.actual-t)/100000)*2000;if(x.target>=180000)return 3500+Math.floor((x.actual-t)/100000)*1200;if(x.target>=100000)return 2000+Math.floor((x.actual-t)/50000)*500;return 1000+Math.floor((x.actual-t)/50000)*500}
function filtered(){let c=$("centre").value,t=$("target").value,q=$("search").value.toLowerCase();return data.filter(x=>(c=="ALL"||x.centre==c)&&(t=="ALL"||(t=="LOW"?x.target<100000:x.target==+t))&&x.name.toLowerCase().includes(q)).sort((a,b)=>b.actual-a.actual)}
function render(){let a=filtered();$("total").textContent=money(a.reduce((s,x)=>s+x.actual,0));$("champion").textContent=a[0]?.name||"—";$("legends").textContent=a.filter(x=>level(x)[2]>=1.5).length;$("count").textContent=a.length;$("rows").textContent=a.length+" participants";let max=Math.max(1500000,...a.map(x=>x.actual),1);$("race").innerHTML=a.map((x,i)=>{let e=level(x),p=Math.min(92,x.actual/max*92);return `<div class="lane"><div class="car" style="left:${p}%">${e[0]}🏎️</div><div class="info">${i+1}. <b>${x.name}</b> · ${x.centre} · ${money(x.actual)} · ${Math.round(e[2]*100)}% · ${e[1]}</div></div>`}).join("")||"<p>No matching participants.</p>";$("table").innerHTML=a.map((x,i)=>{let e=level(x),r=reward(x);return `<tr><td>${i+1}</td><td>${x.name}</td><td>${x.centre}</td><td>${money(x.target)}</td><td>${money(x.target*2)}</td><td>${money(x.actual)}</td><td>${Math.round(e[2]*100)}%</td><td>${e[0]} ${e[1]}</td><td>${r?money(r):"—"}</td></tr>`}).join("");if(a[0])personal(a[0])}
function personal(x){let e=level(x),r=reward(x),next=[1,1.2,1.5].find(v=>v>e[2]);$("personal").innerHTML=`<div class="personal"><h3>${e[0]} ${x.name}</h3><h2>${money(x.actual)}</h2><p>${x.centre} · Target ${money(x.target)} · 2M Target ${money(x.target*2)}</p><p><b>${Math.round(e[2]*100)}% · ${e[1]}</b></p><p>Current Reward: <b>${r?money(r):"$0"}</b></p><p>${next?`Next Level ${Math.round(next*100)}% · Need ${money(Math.max(0,x.target*2*next-x.actual))}`:"All evolution levels unlocked"}</p></div>`}
function centres(){let s=$("centre"),v=s.value;s.innerHTML='<option value="ALL">ALL CENTRE</option>';[...new Set(data.map(x=>x.centre))].sort().forEach(c=>s.innerHTML+=`<option>${c}</option>`);s.value=[...s.options].some(o=>o.value==v)?v:"ALL"}
async function load(){ $("connection").textContent="Connecting to Google Sheet…";try{let r=await fetch(CSV,{cache:"no-store"});if(!r.ok)throw 0;let rows=csv(await r.text());data=rows.slice(1).map((r,i)=>({id:i,centre:(r[0]||"").trim(),name:(r[1]||"").trim(),target:num(r[2]),actual:num(r[3])})).filter(x=>x.name);centres();render();$("connection").textContent="● LIVE DATA · Google Sheet · "+data.length+" rows"}catch(e){$("connection").textContent="⚠ Google Sheet unavailable — check sharing/public access";data=[];render()}}
$("centre").onchange=render;$("target").onchange=render;$("search").oninput=render;$("refresh").onclick=load;load();